services:
  api:
    image: doconnor/movies-api:1.0
    container_name: movies-api
    ports:
      - '9000:9000'
    environment:
      - MONGODB_URI=mongodb://${MONGODB_USERNAME}:${MONGODB_PASSWORD}@mongodb:27017
      - REDIS_URI=redis://redis
      - ENABLE_WRITING_HANDLERS=false

    networks:
      - app_network
      - db_network

    depends_on:
      - mongodb
      - redis

  mongodb:
    image: mongo:8.0-rc

    volumes:
      - mongodb-data:/data/db

    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGODB_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGODB_PASSWORD}

    networks:
      - db_network
      - admin_network

  redis:
    image: redis:alpine

    networks:
      - app_network

  mongo-express:
    image: mongo-express:1.0-20-alpine3.19
    restart: always
    ports:
      - 8080:8081
    profiles:
      - dev # only start this service in the dev profile

    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=${MONGODB_USERNAME}
      - ME_CONFIG_MONGODB_ADMINPASSWORD=${MONGODB_PASSWORD}
      - ME_CONFIG_MONGODB_SERVER=mongodb

    networks:
      - db_network

    depends_on:
      - mongodb

  seeding-mongo:
    image: mongo:8.0-rc
    depends_on:
      - mongodb
    profiles:
      - dev # only start this service in the dev profile
    volumes:
      - ./seeding.json:/seeding.json
      - ./seeding-mongo.sh:/seeding-mongo.sh
    environment:
      - MONGODB_DATABASE=${MONGODB_DATABASE}
      - MONGODB_USERNAME=${MONGODB_USERNAME}
      - MONGODB_PASSWORD=${MONGODB_PASSWORD}
      - MONGODB_URI=mongodb://${MONGODB_USERNAME}:${MONGODB_PASSWORD}@mongodb:27017/${MONGODB_DATABASE}
    command:
      /seeding-mongo.sh
    networks:
      - db_network

networks:
  app_network:
    # movies and redis
    driver: bridge
  db_network:
    # movies and mongodb and seeding-mongo
    driver: bridge
  admin_network:
    # mongo-express and mongodb
    driver: bridge

volumes:
  mongodb-data:
    driver: local
