services:

  api:
    image: doconnor/movies-api:1.0
    container_name: movies-api
    ports:
      - '9000:9000'
    environment:
      - MONGODB_URI=mongodb://${MONGODB_USERNAME}:${MONGODB_PASSWORD}@mongodb:27017/${MONGODB_DATABASE}
      - REDIS_URI=redis://redis
      - ENABLE_WRITING_HANDLERS=false

  mongodb:
    image: mongo:8.0-rc

    volumes:
      - mongodb-data:/data/db

    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGODB_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGODB_PASSWORD}
      - MONGO_INITDB_DATABASE=${MONGODB_DATABASE}


  redis:
    image: redis:alpine

  mongo-express:
    image: mongo-express:1.0-20-alpine3.19

    profiles: 
      - dev # only start this service in the dev profile

    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=${MONGODB_USERNAME}
      - ME_CONFIG_MONGODB_ADMINPASSWORD=${MONGODB_PASSWORD}
      - ME_CONFIG_MONGODB_SERVER=mongodb


  