services:

  api:
    image: doconnor/movies-api:1.0
    container_name: movies-api
    ports:
      - '9000:9000'
    environment:
      - MONGODB_URI=mongodb://${MONGODB_USERNAME}:${MONGODB_PASSWORD}@mongodb:27017/${MONGODB_DATABASE}
      - REDIS_URI=redis://redis
      - ENABLE_WRITING_HANDLERS=false

    networks:
      - app_network
      - db_network

  mongodb:
    image: mongo:8.0-rc

    volumes:
      - mongodb-data:/data/db

    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGODB_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGODB_PASSWORD}
      - MONGO_INITDB_DATABASE=${MONGODB_DATABASE}

    networks:
      - db_network
      - admin_network

  redis:
    image: redis:alpine

    networks:
      - app_network

  mongo-express:
    image: mongo-express:1.0-20-alpine3.19

    profiles: 
      - dev # only start this service in the dev profile

    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=${MONGODB_USERNAME}
      - ME_CONFIG_MONGODB_ADMINPASSWORD=${MONGODB_PASSWORD}
      - ME_CONFIG_MONGODB_SERVER=mongodb

    networks:
      - db_network

networks:
  app_network: # movies and redis
    driver: bridge
  db_network: # movies and mongodb
    driver: bridge
  admin_network: # mongo-express and mongodb
    driver: bridge

volumes:
  mongodb-data:
    driver: local